# Generated by Django 3.0.6 on 2020-05-23 22:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0004_auto_20200523_2256'),
        ('users', '0002_auto_20200516_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='elite_tasker',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='great_tasker',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='our_fees',
            field=models.IntegerField(default=10),
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_qualified', models.BooleanField(default=False)),
                ('rate_per_hour', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('experience', models.CharField(choices=[('ne', 'No Experience'), ('se', 'Some Experience'), ('pt', 'I have had part-time experience'), ('pe', 'I have had professional experience'), ('ip', "I'm professionally")], default='ne', max_length=2)),
                ('toolset', models.TextField(blank=True, null=True)),
                ('quick_summary', models.TextField(blank=True, null=True)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill', to='tasks.Category')),
                ('tasker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_skills', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
