# Generated by Django 3.0.6 on 2020-05-23 22:56

import django.core.validators
from django.db import migrations, models
import tasks.models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_taskdeal'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description_for_skill',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='description_for_skill_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='description_for_skill_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='duration_time',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(8)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='finished_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='description_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=tasks.models.category_image_path),
        ),
    ]
