# Generated by Django 3.0.6 on 2020-05-24 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_auto_20200523_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('p', 'Pending'), ('a', 'active'), ('f', 'Finished'), ('c', 'Canceled')], default='p', max_length=1),
        ),
    ]
