# Generated by Django 3.0.6 on 2020-05-25 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_auto_20200524_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskdeal',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_deal', to='tasks.Task'),
        ),
    ]
