# Generated by Django 3.0.6 on 2020-05-26 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_auto_20200525_1407'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='task_poster',
            new_name='client',
        ),
    ]
